name: 05-06 - Filters and Activity Types
run-name: 05-06 - Filtros y tipos de actividad ${{github.event_name}}
on:
    #push:
    #    branches:
    #        - main
    #pull_request:
    #    types: [opened, synchronize]
    #    branches:
    #        - develop
    workflow_dispatch:
        input:
            debug:
                description: 'Enable Debug mode'
                required: false
                type: boolean
                default: 'false'
jobs:
    echo:
        runs-on:  ubuntu-latest
        env:
            DEBUG_MODE: false
        steps:
            - name: Show Message
              run:  |
                echo 'Workflow triggered by filters or activity types ${{ env.DEBUG_MODE }}'
                
                   

