name: 05-06 - Filters and Activity Types
run-name: 05-06 - Filtros y tipos de actividad ${{github.event_name}}
#env:
#    DEBUG_MODE: false
on:
    workflow_dispatch:
        inputs:
            debug:
                description: 'Enable Debug mode'
                required: false
                type: boolean
                default: false
jobs:
    #env:
    #    DEBUG_MODE: false
    echo:
        runs-on:  ubuntu-latest
        env:
            DEBUG_MODE: true
        steps:
            - name: Show Message
              run:  |
                echo 'Workflow triggered by filters or activity types ${{ env.DEBUG_MODE }}'
                echo 'Workflow triggered by filters or activity types ${{ vars.MY_VAR }}'
                
                   

    #push:
    #    branches:
    #        - main
    #pull_request:
    #    types: [opened, synchronize]
    #    branches:
    #        - develop