name: filters and activities types
on: 
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize]
        branches:
            - main
    workflow_dispatch:
jobs:
    echo:
        runs-on: ubuntu-latest
        
