name: 16 - 2 - Reusable Workflows
on:
  workflow_dispatch:
jobs:
    maindeploy: #.github/workflows/16-1-reusable-workflow.yaml #Miguel8484/rep_prueba/.github/workflows/16-1-reusable-workflow.yaml@main#deploy
        uses: Miguel8226/rep_prueba/.github/workflows/16-1-reusable-workflow.yaml@main
        with:
            target-directory: 'src'
    print-outputs:
        runs-on: ubuntu-latest
        needs: maindeploy
        steps:
            - name: Print outputs
              run: |
                echo "Build status: ${{ needs.maindeploy.outputs.build-status }}"
                echo "Deployed URL: ${{ needs.maindeploy.outputs.url }}"
